name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ยินดีต้อนรับสู่ BMT Open Python Scripts! 👋

            ขอบคุณที่รายงานปัญหา เราจะตรวจสอบและตอบกลับโดยเร็วที่สุด

            ในระหว่างนี้ คุณสามารถ:
            - อ่าน [CONTRIBUTING.md](../CONTRIBUTING.md) เพื่อเรียนรู้วิธีการมีส่วนร่วม
            - ตรวจสอบ [Issues](../issues) ที่มีอยู่เผื่อมีคนรายงานปัญหาเดียวกัน
            - ติดตามการอัปเดตของโปรเจคได้ที่ [GitHub](https://github.com/bemindtech)
          pr-message: |
            ยินดีต้อนรับสู่ BMT Open Python Scripts! 🎉

            ขอบคุณสำหรับ Pull Request แรกของคุณ! เราจะตรวจสอบและให้คำแนะนำโดยเร็วที่สุด

            ในระหว่างนี้ โปรดตรวจสอบว่า:
            - [ ] โค้ดของคุณผ่านการทดสอบทั้งหมด
            - [ ] คุณได้อัปเดตเอกสารที่เกี่ยวข้อง
            - [ ] คุณได้เพิ่มการทดสอบสำหรับฟีเจอร์ใหม่
            - [ ] คุณได้อัปเดต CHANGELOG.md

            หากมีคำถามใดๆ สามารถถามได้ในคอมเมนต์ด้านล่าง
